#!/usr/bin/env python3
"""
Plot F21 (depth noise vs distance) & F22 (%valid pixels vs distance) from REAL measurements.
============================================================================================
Source: docs/astra_noise_vs_distance.csv - generated by
    python tools/astra_depth_range_report.py --mode calib

Unlike tools/gen_mock_figures.py (MOCK curves), this one plots ONLY the real measured points
(+ a theoretical fit line for reference) and writes to KLTN_figures/real_data/ to keep it
transparently separate from the mock part.

Note: the figure axis/title/legend text is kept in Vietnamese to match the thesis figures.

    python tools/plot_astra_noise.py
    python tools/plot_astra_noise.py --csv docs/astra_noise_vs_distance.csv
"""
import argparse
import csv
import os
import sys

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "KLTN_figures", "real_data")
PNG = os.path.join(OUT, "png")


def _f(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return float("nan")


def load_rows(csv_path):
    """Read the calib CSV -> list of dicts, sorted by increasing distance."""
    rows = []
    with open(csv_path, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            rows.append({
                "d_m": _f(r["truth_mm"]) / 1000.0,
                "std": _f(r.get("std_detrend_mm", "")),
                "std_raw": _f(r.get("std_raw_mm", "")),
                "valid_full": _f(r.get("valid_full_pct", "")),
                "valid_center": _f(r.get("valid_center_pct", "")),
                "median_mm": _f(r.get("median_mm", "")),
            })
    rows.sort(key=lambda x: x["d_m"])
    return rows


def fig_f21(rows):
    pts = [(r["d_m"], r["std"]) for r in rows if np.isfinite(r["std"])]
    if not pts:
        print("[F21] skip - no valid std column yet.")
        return
    d = np.array([p[0] for p in pts])
    s = np.array([p[1] for p in pts])
    fig, ax = plt.subplots(figsize=(6.5, 4))
    ax.plot(d, s, "o-", color="#8172B3", label="Độ lệch chuẩn depth")
    # Fit std = a*d^2 (through the origin) to verify the ∝ d^2 relationship
    if len(d) >= 3:
        a = float(np.sum(s * d ** 2) / np.sum(d ** 4))
        dd = np.linspace(d.min(), d.max(), 50)
        ax.plot(dd, a * dd ** 2, "--", color="gray",
                label=f"Khớp std ≈ {a:.1f}·d² (mm)")
    ax.axvline(1.022, ls="--", color="red", label="Trần tầm ~1022 mm")
    ax.set_xlabel("Khoảng cách (m)")
    ax.set_ylabel("Độ lệch chuẩn depth (mm)")
    ax.set_title("Astra — Độ nhiễu depth theo cự ly")
    ax.legend()
    ax.grid(alpha=0.3)
    _save(fig, "f21_depth_noise_vs_distance_real")


def fig_f22(rows):
    pts = [(r["d_m"], r["valid_full"]) for r in rows if np.isfinite(r["valid_full"])]
    if not pts:
        print("[F22] skip - no valid valid_full column yet.")
        return
    d = np.array([p[0] for p in pts])
    v = np.array([p[1] for p in pts])
    fig, ax = plt.subplots(figsize=(6.5, 4))
    ax.plot(d, v, "o-", color="#55A868", label="% pixel depth hợp lệ")
    # 50% drop-off point (linear interpolation between the two points bracketing 50%)
    cross = _cross_50(d, v)
    if cross is not None:
        ax.axvline(cross, ls=":", color="#55A868",
                   label=f"Điểm rơi 50% ≈ {cross:.2f} m")
    ax.axvline(1.022, ls="--", color="red", label="Trần tầm ~1022 mm")
    ax.set_xlabel("Khoảng cách (m)")
    ax.set_ylabel("% pixel depth hợp lệ")
    ax.set_ylim(-3, 103)
    ax.set_title("Astra — Tỉ lệ pixel hợp lệ theo cự ly")
    ax.legend()
    ax.grid(alpha=0.3)
    _save(fig, "f22_depth_valid_ratio_real")


def _cross_50(d, v):
    for i in range(len(d) - 1):
        if (v[i] - 50) * (v[i + 1] - 50) <= 0 and v[i] != v[i + 1]:
            t = (50 - v[i]) / (v[i + 1] - v[i])
            return float(d[i] + t * (d[i + 1] - d[i]))
    return None


def _save(fig, name):
    os.makedirs(PNG, exist_ok=True)
    path = os.path.join(PNG, name + ".png")
    fig.savefig(path, bbox_inches="tight", dpi=120)
    plt.close(fig)
    print(f">> {path}")


def main():
    ap = argparse.ArgumentParser(description="Plot F21/F22 from real measurements")
    ap.add_argument("--csv", default=os.path.join("docs", "astra_noise_vs_distance.csv"))
    args = ap.parse_args()
    csv_path = args.csv if os.path.isabs(args.csv) else os.path.join(ROOT, args.csv)
    if not os.path.exists(csv_path):
        print(f"[ERR] Missing CSV: {csv_path}\n"
              "      Run first: python tools/astra_depth_range_report.py --mode calib",
              file=sys.stderr)
        return 2
    rows = load_rows(csv_path)
    if not rows:
        print("[ERR] Empty CSV.", file=sys.stderr)
        return 2
    print(f">> {len(rows)} distance points from {csv_path}")
    fig_f21(rows)
    fig_f22(rows)
    print("DONE - F21/F22 (real) ->", PNG)
    return 0


if __name__ == "__main__":
    sys.exit(main())
